### ISSUE TITLE
matrix: figure out why receiving messages dies

### ISSUE THREAD

**Issue by TheSchwa** [TheSchwa/sibyl#28]
Sometimes receiving messages from matrix will stop working while sending messages functions normally. This has been observed (to very annoying effect) in bridges.

These (possible relevant) log lines have been observed in the neighborhood of the problem:

```
2017-08-15 19:54:52 | matrix   | DEB | Incoming message did not have all required fields: msgtype
2017-08-15 19:55:48 | matrix   | DEB | Incoming message did not have all required fields: msgtype
```

Probably need to enable the `matrix.debug` config option for further testing. Catching the bot in this state and exploring the Matrix Protocol object and the api object it contains should also be interesting. For example:

```
#eval dir(bot.get_protocol('matrix').client)
```

This seems like an issue with the python API though; probably worth it to see if there are any relevant looking bugs open upstream.

**Comment by TheSchwa** [comment]
Appears to be caused by a simple disconnect. If the listener thread dies, then sibyl won't receive messages from matrix. However, as sending a message *to* matrix creates a new connection, that works normally.

```
2017-09-12 00:08:45 | matrix   | DEB | Handling m.text: [1] So much for that Voynich manuscript “solution” | Ars Technica

2017-09-12 02:06:27 | xmpp     | ERR | Connection lost (ping timeout); retrying in 60 sec
2017-09-12 02:07:27 | xmpp     | DEB | Attempting to connect with JID "sibyl@terracrypt.net"

2017-09-12 02:08:01 | matrix_c | ERR | Exception thrown during sync
Traceback (most recent call last):
  File "/home/sibyl/sibyl/src/matrix-client/matrix_client/client.py", line 356, in listen_forever
    self._sync(timeout_ms)
  File "/home/sibyl/sibyl/src/matrix-client/matrix_client/client.py", line 455, in _sync
    response = self.api.sync(self.sync_token, timeout_ms, filter=self.sync_filter)
  File "/home/sibyl/sibyl/src/matrix-client/matrix_client/api.py", line 94, in sync
    api_path=MATRIX_V2_API_PATH)
  File "/home/sibyl/sibyl/src/matrix-client/matrix_client/api.py", line 563, in _send
    verify=self.validate_cert
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='terracrypt.net', port=443): Max retries exceeded with url: /_matrix/client/r0/sync?filter=%7B+%22room%22%3A+%7B+%22timeline%22+%3A+%7B+%22limit%22+%3A+20+%7D+%7D+%7D&access_token=MDAxY2xvY2F0aW9uIHRlcnJhY3J5cHQubmV0CjAwMTNpZGVudGlmaWVyIGtleQowMDEwY2lkIGdlbiA9IDEKMDAyOGNpZCB1c2VyX2lkID0gQHNpYnlsOnRlcnJhY3J5cHQubmV0CjAwMTZjaWQgdHlwZSA9IGFjY2VzcwowMDIxY2lkIG5vbmNlID0gQ2VzUXlWWX5iWDJvQTVzMQowMDJmc2lnbmF0dXJlIJv_5mgrKsiqBql8XLm9V20EoeWb66kVocMHTNlR05VxCg&since=s3994771_36459098_300522_3920836_19416_316_11563_90332&timeout=30000 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa91a7efc10>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

The relevant method allows you to specify an exception handler, so inside that you can just put he exception on `sibyl_matrx`'s internal message queue. Then in `process()` check the object type when popping it off the queue and raise a Sibyl-friendly exception (e.g. `ConnectFailure`) in response. Sibyl will then handle reconnecting without further action.

Matrix and bridge recovered completely after just reconnecting the protocol:
```
#eval bot.get_protocol('matrix').connect()
```

**Comment by TheSchwa** [comment]
Depending on how you implement this, the exception handling might have to get modified if/when this PR gets merged:
https://github.com/matrix-org/matrix-python-sdk/pull/123/files

**Comment by jfrederickson** [comment]
Welp, I wasn't able to repro the issue I was seeing before when I tried to fix this - possible it's been fixed in a newer version of the Python SDK. I'm going to merge my last attempt at fixing this since I can verify it works.
